# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourhood_location', models.CharField(max_length=40)),
                ('neighbourhood_name', models.CharField(max_length=40)),
                ('occupants_count', models.IntegerField(default=0)),
                ('area', pyuploadcare.dj.models.ImageField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
