# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='neighbourhood_location',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='neighbourhood_name',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
