# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
