# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0008_business_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neighbourhood',
        ),
    ]
